### ISSUE TITLE
Error: Argument shapes are inconsistent

### ISSUE THREAD

**Issue by OmPrakash4** [bes-dev/random_face#6]
I am getting an error while trying a simple program. Could you please assist on how to fix this issue.

engine = random_face.get_engine()
random_face = engine.get_random_face()

Traceback (most recent call last):
  File "./scripts/generate_random_fvs.py", line 8, in <module>
    engine = random_face.get_engine()
  File "/home/omprakash/github/CassiniServer/venv/lib/python3.8/site-packages/random_face/random_face.py", line 29, in get_engine
    return EngineOpenvino(cfg)
  File "/home/omprakash/github/CassiniServer/venv/lib/python3.8/site-packages/random_face/engine_openvino.py", line 39, in __init__
    self.snet_exec = self.ie.load_network(network=self.snet, device_name="CPU")
  File "ie_api.pyx", line 413, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 457, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Check 'PartialShape::broadcast_merge_into(pshape, node->get_input_partial_shape(i), autob)' failed at core/src/op/util/elementwise_args.cpp:30:
While validating node 'v1::Multiply Multiply_9566 (Mul_39_copy[0]:f32{512,512,3,3}, Constant_9519[0]:f32{1,512,4,4}) -> (dynamic...)' with friendly_name 'Multiply_9566':
Argument shapes are inconsistent.

**Comment by comprakash** [comment]
The issue was fixed by specifying the openvino library version to 2021.4.2.

Have raised the pull request for this. Please review. Thanks.

**Comment by hamedmh** [comment]
> The issue was fixed by specifying the openvino library version to 2021.4.2.
> 
> Have raised the pull request for this. Please review. Thanks.
Hi @comprakash !
I need to know how to install openvino library version to 2021.4.2  instead of the latest version that is installed and causes this problem.  Thanks a lot!
